#!/usr/bin/env node

var app = require('../');

app.version = '0.0.1';

app.language('zh-CN');

app
  .option('-f, --foo', 'enable some foo')
  .option('-b, --bar', 'enable some bar')
  .option('-B, --baz', 'enable some baz');

// must be before .listen() since the help is immediate

app.customHelp = function () {
    var example;
    example = this.language.help.title.example;
    example = this.setStyle(example, 'bold', 'underline');

    this.showHelp(function (message) {
        message = [message].concat([
            '  ' + example,
            '',
            '    $ custom-help --help',
            '    $ custom-help -h',
            ''
        ]).join('\n');

        return message;
    });
};

app.listen();