#!/usr/bin/env node

var app = require('../');

function list(val) {
  return val.split(',').map(Number);
}

app.version = '0.0.1';

app
  .option('-t, --template-engine [engine]', 'Add template [engine] support', 'jade')
  .option('-c, --cheese [type]', 'Add the specified type of cheese [marble]', 'marble')
  .option('-l, --list [items]', 'Specify list items defaulting to 1,2,3', list, [1,2,3])
  .listen();

console.log('  - %s template engine', app.options.templateEngine);
console.log('  - %s cheese', app.options.cheese);
console.log('  - %j', app.options.list);
