#!/usr/bin/env node

var app = require('..');

app.version = '0.0.1';

app
    .describe('命令行点餐系统')
    .option('-m, --meat', '辣椒炒肉')
    .option('-f, --fish', '双椒鱼头')
    .option('-e, --eggplant', '茄子豆角')
    .option('-d, --drink [type]', '选择饮料 [冰镇绿豆汤]')
    .listen();

console.log('你点的套餐包含:');
if (app.options.meat) console.log('  - 辣椒炒肉');
if (app.options.fish) console.log('  - 双椒鱼头');
if (app.options.eggplant) console.log('  - 茄子豆角');

var drink = true === app.options.drink
    ? '冰镇绿豆汤'
    : app.options.drink || '不要饮料';

console.log('  - %s', drink);
console.log(app.args);