#!/usr/bin/env node

var app = require('..');

app
  .option('-f, --force', 'force installation')
  .listen();

var pkgs = app.args;

if (!pkgs.length) {
  console.error('packages required');
  process.exit(1);
}

console.log();
if (app.options.force) console.log('  force: install');
pkgs.forEach(function(pkg){
  console.log('  install : %s', pkg);
});
console.log();
