#!/usr/bin/env node

var app = require('..');

app.version = '0.0.1';

app
    .command('help')
    .describe('show help information for this command')
    .option('-s --show', 'show help information or not')
    .action(function(options) {
        this.showHelp();          // show help for current command
    });

if (!process.argv.slice(2).length) {
    app.showHelp();     // show help for default command
}

app.listen();